"""
Path configuration variables for the project workspace.
"""

from analytica.core.constants.paths_constants import (
    DEFAULT_CONFIG_DIR,
    DEFAULT_DATA_DIR,
    DEFAULT_DOCS_DIR,
    DEFAULT_ENV_FILE,
    DEFAULT_EXTERNAL_DATA_DIR,
    DEFAULT_FIGURES_DIR,
    DEFAULT_INTERIM_DATA_DIR,
    DEFAULT_LOG_DIR,
    DEFAULT_MODELS_DIR,
    DEFAULT_NOTEBOOKS_DIR,
    DEFAULT_PROCESSED_DATA_DIR,
    DEFAULT_PROMPT_DIR,
    DEFAULT_RAW_DATA_DIR,
    DEFAULT_REPORTS_DIR,
    DEFAULT_TESTS_DIR,
)
from analytica.core.constants.providers_constants import (
    DEFAULT_LLM_PROVIDER_PARAM_FILE,
)
from analytica.utils.get_root import get_root

from ..constants.project_constants import PROJECT_NAME

ROOT_DIR = get_root()

# Data paths
DATA_DIR = ROOT_DIR / DEFAULT_DATA_DIR
RAW_DATA_DIR = DATA_DIR / DEFAULT_RAW_DATA_DIR
INTERIM_DATA_DIR = DATA_DIR / DEFAULT_INTERIM_DATA_DIR
PROCESSED_DATA_DIR = DATA_DIR / DEFAULT_PROCESSED_DATA_DIR
EXTERNAL_DATA_DIR = DATA_DIR / DEFAULT_EXTERNAL_DATA_DIR

# Artifacts and outputs
MODELS_DIR = ROOT_DIR / DEFAULT_MODELS_DIR
REPORTS_DIR = ROOT_DIR / DEFAULT_REPORTS_DIR
FIGURES_DIR = REPORTS_DIR / DEFAULT_FIGURES_DIR

# Project structure
LOG_DIR = ROOT_DIR / DEFAULT_LOG_DIR
CONFIG_DIR = ROOT_DIR / DEFAULT_CONFIG_DIR
NOTEBOOKS_DIR = ROOT_DIR / DEFAULT_NOTEBOOKS_DIR
DOCS_DIR = ROOT_DIR / DEFAULT_DOCS_DIR
TESTS_DIR = ROOT_DIR / DEFAULT_TESTS_DIR

# Environment file
ENV_FILE = ROOT_DIR / DEFAULT_ENV_FILE

# Provider (Groq)
DEFAULT_CONFIG_PATH = ROOT_DIR / DEFAULT_CONFIG_DIR / DEFAULT_LLM_PROVIDER_PARAM_FILE

# Prompt Path
DEFAULT_PROMPT_DIR_PATH = ROOT_DIR / PROJECT_NAME / DEFAULT_PROMPT_DIR

__all__ = [
    "CONFIG_DIR",
    "DATA_DIR",
    "DEFAULT_CONFIG_PATH",
    "DEFAULT_PROMPT_DIR_PATH",
    "DOCS_DIR",
    "ENV_FILE",
    "EXTERNAL_DATA_DIR",
    "FIGURES_DIR",
    "INTERIM_DATA_DIR",
    "LOG_DIR",
    "MODELS_DIR",
    "NOTEBOOKS_DIR",
    "PROCESSED_DATA_DIR",
    "RAW_DATA_DIR",
    "REPORTS_DIR",
    "ROOT_DIR",
    "TESTS_DIR",
]
